In [3]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, ShuffleSplit, GridSearchCV
from sklearn import svm
from sklearn import metrics
from sklearn.preprocessing import LabelEncoder

In [4]:
#Question 1
df = pd.read_csv("College.csv")
df

labelencoder = LabelEncoder()
df["Private"] = labelencoder.fit_transform(df["Private"])
df

,Private,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate
0,1,1660,1232,721,23,52,2885,537,7440,3300,450,2200,70,78,18.1,12,7041,60
1,1,2186,1924,512,16,29,2683,1227,12280,6450,750,1500,29,30,12.2,16,10527,56
2,1,1428,1097,336,22,50,1036,99,11250,3750,400,1165,53,66,12.9,30,8735,54
3,1,417,349,137,60,89,510,63,12960,5450,450,875,92,97,7.7,37,19016,59
4,1,193,146,55,16,44,249,869,7560,4120,800,1500,76,72,11.9,2,10922,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
772,0,2197,1515,543,4,26,3089,2029,6797,3900,500,1200,60,60,21.0,14,4469,40
773,1,1959,1805,695,24,47,2849,1107,11520,4960,600,1250,73,75,13.3,31,9189,83
774,1,2097,1915,695,34,61,2793,166,6900,4200,617,781,67,75,14.4,20,8323,49
775,1,10705,2453,1317,95,99,5217,83,19840,6510,630,2115,96,96,5.8,49,40386,99
776,1,2989,1855,691,28,63,2988,1726,4990,3560,500,1250,75,75,18.1,28,4509,99

In [5]:
#Question 2
x = df.iloc[:, 1:]
y = df["Private"]

train_x, test_x, train_y, test_y = train_test_split(
    x, y, random_state=10,test_size=0.25)

In [6]:
#Question 3
svm = svm.LinearSVC()
svm.fit(train_x, train_y)
predictedVals = svm.predict(test_x)

print("Accuracy Score:",metrics.accuracy_score(predictedVals, test_y))

Accuracy Score: 0.8461538461538461

/opt/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

In [21]:
#Question 4
from sklearn.svm import LinearSVC, SVC
scaler = StandardScaler().fit_transform(x)
scaler = pd.DataFrame(x, columns=x.columns)

x = scaler
y = df["Private"]

train_x, test_x, train_y, test_y = train_test_split(
    x, y, random_state=10, test_size=0.25)

svm = LinearSVC()
svm.fit(train_x, train_y)

predictedVals = svm.predict(test_x)
metrics.accuracy_score(predictedVals, test_y)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

0.9282051282051282

In [28]:
#Question 5
parameter = [
    {'C': [1, 10, 100, 1000], 'kernel': ['poly']},
    {'C': [1, 10, 100, 1000], 'kernel': ['linear']},
    {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001], 'kernel': ['rbf']},
]

# Create a classifier object with the classifier and parameter candidates
cv = ShuffleSplit()
clf = GridSearchCV(estimator=SVC(max_iter=1000),
                   param_grid=parameter, n_jobs=-1, cv=cv)

# Train the classifier on data1's feature and target data
clf.fit(train_x, train_y)

# View the accuracy score
print('Best score for data1:', clf.best_score_)

# View the best parameters for the model found using grid search
print('Best C:', clf.best_estimator_.C)
print('Best Kernel:', clf.best_estimator_.kernel)
print('Best Gamma:', clf.best_estimator_.gamma)

Best score for data1: 0.8152542372881356
Best C: 1
Best Kernel: linear
Best Gamma: auto_deprecated

/opt/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)